# Generated by Django 4.1.7 on 2023-03-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_id_order_orderid_orderitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='subtotal',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
